### ISSUE TITLE
Regarding the comment box

### ISSUE THREAD

**Issue by sjtsh** [kunga2050453/Collab#15]
Apart from responsiveness and better design for the comment box please make the comment section part of the page fixed so the scrolling of the page does not affect the comment box.
![image](https://user-images.githubusercontent.com/74091619/118269580-a772f380-b4de-11eb-943f-663e79e5b72f.png)

**Comment by sandesh-srg** [comment]
The issue is fixed
![Screenshot (124)](https://user-images.githubusercontent.com/81897295/118393368-a97aa680-b5f3-11eb-8340-4ff989ab35d3.png)
