### ISSUE TITLE
With respect to Admin page

### ISSUE THREAD

**Issue by sjtsh** [kunga2050453/Collab#9]
Some minor improvements are to be made with accord to the background. Also, note to add "go to user feed" button, change the heading to "admin page" and add a add admin button such that any admin is allowed to add emails and those emails would be 
 allowed to sign up for admin.
![Screenshot (148)](https://user-images.githubusercontent.com/74091619/115948424-0c45ba00-a4ee-11eb-9d8e-234d0dce7e04.png)

**Comment by SwarinShakya** [comment]
I have completed what you have suggested in tis issue.
